logging:
  level:
    org.springframework: DEBUG
    org.apache.kafka: DEBUG

spring:
  kafka:
    bootstrap-servers: mulmuri.dev:9092
    producer:
      bootstrap-servers: mulmuri.dev:9092
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: io.goboolean.streams.serde.JsonAggregateSerde.JsonSerializer
    consumer:
      group-id: myGroup
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.goboolean.streams.serde.JsonTradeSerde.JsonDeserializer
      auto-offset-reset: earliest