spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: myGroup
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: io.goboolean.streams.serde.AggregateSerde.JsonDeserializer
      auto-offset-reset: earliest

etcd:
  endpoints: ${ETCD_ENDPOINTS}

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
  application-id-config: KAFKA_STREAMS_APP

open-telemetry:
  endpoint: http://mulmuri.dev:4317
  service-name: fetch-system.streams
  service-version: 0.1.0

logging:
  config: classpath:log4j2.xml
  level:
    io.goboolean: INFO
    org.springframework.boot: INFO
