// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/model.proto

package io.goboolean.streams.serde;

public final class Model {
  private Model() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TradeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Trade)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>double price = 1;</code>
     * @return The price.
     */
    double getPrice();

    /**
     * <code>int64 size = 2;</code>
     * @return The size.
     */
    long getSize();

    /**
     * <code>int64 timestamp = 3;</code>
     * @return The timestamp.
     */
    long getTimestamp();
  }
  /**
   * Protobuf type {@code Trade}
   */
  public static final class Trade extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Trade)
      TradeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Trade.newBuilder() to construct.
    private Trade(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Trade() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Trade();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.goboolean.streams.serde.Model.internal_static_Trade_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.goboolean.streams.serde.Model.internal_static_Trade_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.goboolean.streams.serde.Model.Trade.class, io.goboolean.streams.serde.Model.Trade.Builder.class);
    }

    public static final int PRICE_FIELD_NUMBER = 1;
    private double price_ = 0D;
    /**
     * <code>double price = 1;</code>
     * @return The price.
     */
    @java.lang.Override
    public double getPrice() {
      return price_;
    }

    public static final int SIZE_FIELD_NUMBER = 2;
    private long size_ = 0L;
    /**
     * <code>int64 size = 2;</code>
     * @return The size.
     */
    @java.lang.Override
    public long getSize() {
      return size_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 3;
    private long timestamp_ = 0L;
    /**
     * <code>int64 timestamp = 3;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (java.lang.Double.doubleToRawLongBits(price_) != 0) {
        output.writeDouble(1, price_);
      }
      if (size_ != 0L) {
        output.writeInt64(2, size_);
      }
      if (timestamp_ != 0L) {
        output.writeInt64(3, timestamp_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (java.lang.Double.doubleToRawLongBits(price_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, price_);
      }
      if (size_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, size_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, timestamp_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.goboolean.streams.serde.Model.Trade)) {
        return super.equals(obj);
      }
      io.goboolean.streams.serde.Model.Trade other = (io.goboolean.streams.serde.Model.Trade) obj;

      if (java.lang.Double.doubleToLongBits(getPrice())
          != java.lang.Double.doubleToLongBits(
              other.getPrice())) return false;
      if (getSize()
          != other.getSize()) return false;
      if (getTimestamp()
          != other.getTimestamp()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PRICE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getPrice()));
      hash = (37 * hash) + SIZE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSize());
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.goboolean.streams.serde.Model.Trade parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.goboolean.streams.serde.Model.Trade parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.goboolean.streams.serde.Model.Trade parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.goboolean.streams.serde.Model.Trade parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.goboolean.streams.serde.Model.Trade parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.goboolean.streams.serde.Model.Trade parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.goboolean.streams.serde.Model.Trade parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.goboolean.streams.serde.Model.Trade parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.goboolean.streams.serde.Model.Trade parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.goboolean.streams.serde.Model.Trade parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.goboolean.streams.serde.Model.Trade parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.goboolean.streams.serde.Model.Trade parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.goboolean.streams.serde.Model.Trade prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Trade}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Trade)
        io.goboolean.streams.serde.Model.TradeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.goboolean.streams.serde.Model.internal_static_Trade_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.goboolean.streams.serde.Model.internal_static_Trade_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.goboolean.streams.serde.Model.Trade.class, io.goboolean.streams.serde.Model.Trade.Builder.class);
      }

      // Construct using io.goboolean.streams.serde.Model.Trade.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        price_ = 0D;
        size_ = 0L;
        timestamp_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.goboolean.streams.serde.Model.internal_static_Trade_descriptor;
      }

      @java.lang.Override
      public io.goboolean.streams.serde.Model.Trade getDefaultInstanceForType() {
        return io.goboolean.streams.serde.Model.Trade.getDefaultInstance();
      }

      @java.lang.Override
      public io.goboolean.streams.serde.Model.Trade build() {
        io.goboolean.streams.serde.Model.Trade result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.goboolean.streams.serde.Model.Trade buildPartial() {
        io.goboolean.streams.serde.Model.Trade result = new io.goboolean.streams.serde.Model.Trade(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(io.goboolean.streams.serde.Model.Trade result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.price_ = price_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.size_ = size_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.timestamp_ = timestamp_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.goboolean.streams.serde.Model.Trade) {
          return mergeFrom((io.goboolean.streams.serde.Model.Trade)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.goboolean.streams.serde.Model.Trade other) {
        if (other == io.goboolean.streams.serde.Model.Trade.getDefaultInstance()) return this;
        if (other.getPrice() != 0D) {
          setPrice(other.getPrice());
        }
        if (other.getSize() != 0L) {
          setSize(other.getSize());
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 9: {
                price_ = input.readDouble();
                bitField0_ |= 0x00000001;
                break;
              } // case 9
              case 16: {
                size_ = input.readInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                timestamp_ = input.readInt64();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private double price_ ;
      /**
       * <code>double price = 1;</code>
       * @return The price.
       */
      @java.lang.Override
      public double getPrice() {
        return price_;
      }
      /**
       * <code>double price = 1;</code>
       * @param value The price to set.
       * @return This builder for chaining.
       */
      public Builder setPrice(double value) {
        
        price_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>double price = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPrice() {
        bitField0_ = (bitField0_ & ~0x00000001);
        price_ = 0D;
        onChanged();
        return this;
      }

      private long size_ ;
      /**
       * <code>int64 size = 2;</code>
       * @return The size.
       */
      @java.lang.Override
      public long getSize() {
        return size_;
      }
      /**
       * <code>int64 size = 2;</code>
       * @param value The size to set.
       * @return This builder for chaining.
       */
      public Builder setSize(long value) {
        
        size_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int64 size = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSize() {
        bitField0_ = (bitField0_ & ~0x00000002);
        size_ = 0L;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>int64 timestamp = 3;</code>
       * @return The timestamp.
       */
      @java.lang.Override
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>int64 timestamp = 3;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int64 timestamp = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000004);
        timestamp_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Trade)
    }

    // @@protoc_insertion_point(class_scope:Trade)
    private static final io.goboolean.streams.serde.Model.Trade DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.goboolean.streams.serde.Model.Trade();
    }

    public static io.goboolean.streams.serde.Model.Trade getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Trade>
        PARSER = new com.google.protobuf.AbstractParser<Trade>() {
      @java.lang.Override
      public Trade parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Trade> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Trade> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.goboolean.streams.serde.Model.Trade getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AggregateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Aggregate)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>double open = 1;</code>
     * @return The open.
     */
    double getOpen();

    /**
     * <code>double closed = 2;</code>
     * @return The closed.
     */
    double getClosed();

    /**
     * <code>double min = 3;</code>
     * @return The min.
     */
    double getMin();

    /**
     * <code>double max = 4;</code>
     * @return The max.
     */
    double getMax();

    /**
     * <code>int64 volume = 5;</code>
     * @return The volume.
     */
    long getVolume();

    /**
     * <code>int64 timestamp = 6;</code>
     * @return The timestamp.
     */
    long getTimestamp();
  }
  /**
   * Protobuf type {@code Aggregate}
   */
  public static final class Aggregate extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Aggregate)
      AggregateOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Aggregate.newBuilder() to construct.
    private Aggregate(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Aggregate() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Aggregate();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.goboolean.streams.serde.Model.internal_static_Aggregate_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.goboolean.streams.serde.Model.internal_static_Aggregate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.goboolean.streams.serde.Model.Aggregate.class, io.goboolean.streams.serde.Model.Aggregate.Builder.class);
    }

    public static final int OPEN_FIELD_NUMBER = 1;
    private double open_ = 0D;
    /**
     * <code>double open = 1;</code>
     * @return The open.
     */
    @java.lang.Override
    public double getOpen() {
      return open_;
    }

    public static final int CLOSED_FIELD_NUMBER = 2;
    private double closed_ = 0D;
    /**
     * <code>double closed = 2;</code>
     * @return The closed.
     */
    @java.lang.Override
    public double getClosed() {
      return closed_;
    }

    public static final int MIN_FIELD_NUMBER = 3;
    private double min_ = 0D;
    /**
     * <code>double min = 3;</code>
     * @return The min.
     */
    @java.lang.Override
    public double getMin() {
      return min_;
    }

    public static final int MAX_FIELD_NUMBER = 4;
    private double max_ = 0D;
    /**
     * <code>double max = 4;</code>
     * @return The max.
     */
    @java.lang.Override
    public double getMax() {
      return max_;
    }

    public static final int VOLUME_FIELD_NUMBER = 5;
    private long volume_ = 0L;
    /**
     * <code>int64 volume = 5;</code>
     * @return The volume.
     */
    @java.lang.Override
    public long getVolume() {
      return volume_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 6;
    private long timestamp_ = 0L;
    /**
     * <code>int64 timestamp = 6;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (java.lang.Double.doubleToRawLongBits(open_) != 0) {
        output.writeDouble(1, open_);
      }
      if (java.lang.Double.doubleToRawLongBits(closed_) != 0) {
        output.writeDouble(2, closed_);
      }
      if (java.lang.Double.doubleToRawLongBits(min_) != 0) {
        output.writeDouble(3, min_);
      }
      if (java.lang.Double.doubleToRawLongBits(max_) != 0) {
        output.writeDouble(4, max_);
      }
      if (volume_ != 0L) {
        output.writeInt64(5, volume_);
      }
      if (timestamp_ != 0L) {
        output.writeInt64(6, timestamp_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (java.lang.Double.doubleToRawLongBits(open_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, open_);
      }
      if (java.lang.Double.doubleToRawLongBits(closed_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, closed_);
      }
      if (java.lang.Double.doubleToRawLongBits(min_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, min_);
      }
      if (java.lang.Double.doubleToRawLongBits(max_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, max_);
      }
      if (volume_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, volume_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, timestamp_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.goboolean.streams.serde.Model.Aggregate)) {
        return super.equals(obj);
      }
      io.goboolean.streams.serde.Model.Aggregate other = (io.goboolean.streams.serde.Model.Aggregate) obj;

      if (java.lang.Double.doubleToLongBits(getOpen())
          != java.lang.Double.doubleToLongBits(
              other.getOpen())) return false;
      if (java.lang.Double.doubleToLongBits(getClosed())
          != java.lang.Double.doubleToLongBits(
              other.getClosed())) return false;
      if (java.lang.Double.doubleToLongBits(getMin())
          != java.lang.Double.doubleToLongBits(
              other.getMin())) return false;
      if (java.lang.Double.doubleToLongBits(getMax())
          != java.lang.Double.doubleToLongBits(
              other.getMax())) return false;
      if (getVolume()
          != other.getVolume()) return false;
      if (getTimestamp()
          != other.getTimestamp()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + OPEN_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getOpen()));
      hash = (37 * hash) + CLOSED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getClosed()));
      hash = (37 * hash) + MIN_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getMin()));
      hash = (37 * hash) + MAX_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getMax()));
      hash = (37 * hash) + VOLUME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getVolume());
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.goboolean.streams.serde.Model.Aggregate parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.goboolean.streams.serde.Model.Aggregate parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.goboolean.streams.serde.Model.Aggregate parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.goboolean.streams.serde.Model.Aggregate parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.goboolean.streams.serde.Model.Aggregate parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.goboolean.streams.serde.Model.Aggregate parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.goboolean.streams.serde.Model.Aggregate parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.goboolean.streams.serde.Model.Aggregate parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.goboolean.streams.serde.Model.Aggregate parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.goboolean.streams.serde.Model.Aggregate parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.goboolean.streams.serde.Model.Aggregate parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.goboolean.streams.serde.Model.Aggregate parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.goboolean.streams.serde.Model.Aggregate prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Aggregate}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Aggregate)
        io.goboolean.streams.serde.Model.AggregateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.goboolean.streams.serde.Model.internal_static_Aggregate_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.goboolean.streams.serde.Model.internal_static_Aggregate_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.goboolean.streams.serde.Model.Aggregate.class, io.goboolean.streams.serde.Model.Aggregate.Builder.class);
      }

      // Construct using io.goboolean.streams.serde.Model.Aggregate.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        open_ = 0D;
        closed_ = 0D;
        min_ = 0D;
        max_ = 0D;
        volume_ = 0L;
        timestamp_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.goboolean.streams.serde.Model.internal_static_Aggregate_descriptor;
      }

      @java.lang.Override
      public io.goboolean.streams.serde.Model.Aggregate getDefaultInstanceForType() {
        return io.goboolean.streams.serde.Model.Aggregate.getDefaultInstance();
      }

      @java.lang.Override
      public io.goboolean.streams.serde.Model.Aggregate build() {
        io.goboolean.streams.serde.Model.Aggregate result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.goboolean.streams.serde.Model.Aggregate buildPartial() {
        io.goboolean.streams.serde.Model.Aggregate result = new io.goboolean.streams.serde.Model.Aggregate(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(io.goboolean.streams.serde.Model.Aggregate result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.open_ = open_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.closed_ = closed_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.min_ = min_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.max_ = max_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.volume_ = volume_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.timestamp_ = timestamp_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.goboolean.streams.serde.Model.Aggregate) {
          return mergeFrom((io.goboolean.streams.serde.Model.Aggregate)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.goboolean.streams.serde.Model.Aggregate other) {
        if (other == io.goboolean.streams.serde.Model.Aggregate.getDefaultInstance()) return this;
        if (other.getOpen() != 0D) {
          setOpen(other.getOpen());
        }
        if (other.getClosed() != 0D) {
          setClosed(other.getClosed());
        }
        if (other.getMin() != 0D) {
          setMin(other.getMin());
        }
        if (other.getMax() != 0D) {
          setMax(other.getMax());
        }
        if (other.getVolume() != 0L) {
          setVolume(other.getVolume());
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 9: {
                open_ = input.readDouble();
                bitField0_ |= 0x00000001;
                break;
              } // case 9
              case 17: {
                closed_ = input.readDouble();
                bitField0_ |= 0x00000002;
                break;
              } // case 17
              case 25: {
                min_ = input.readDouble();
                bitField0_ |= 0x00000004;
                break;
              } // case 25
              case 33: {
                max_ = input.readDouble();
                bitField0_ |= 0x00000008;
                break;
              } // case 33
              case 40: {
                volume_ = input.readInt64();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 48: {
                timestamp_ = input.readInt64();
                bitField0_ |= 0x00000020;
                break;
              } // case 48
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private double open_ ;
      /**
       * <code>double open = 1;</code>
       * @return The open.
       */
      @java.lang.Override
      public double getOpen() {
        return open_;
      }
      /**
       * <code>double open = 1;</code>
       * @param value The open to set.
       * @return This builder for chaining.
       */
      public Builder setOpen(double value) {
        
        open_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>double open = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearOpen() {
        bitField0_ = (bitField0_ & ~0x00000001);
        open_ = 0D;
        onChanged();
        return this;
      }

      private double closed_ ;
      /**
       * <code>double closed = 2;</code>
       * @return The closed.
       */
      @java.lang.Override
      public double getClosed() {
        return closed_;
      }
      /**
       * <code>double closed = 2;</code>
       * @param value The closed to set.
       * @return This builder for chaining.
       */
      public Builder setClosed(double value) {
        
        closed_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>double closed = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearClosed() {
        bitField0_ = (bitField0_ & ~0x00000002);
        closed_ = 0D;
        onChanged();
        return this;
      }

      private double min_ ;
      /**
       * <code>double min = 3;</code>
       * @return The min.
       */
      @java.lang.Override
      public double getMin() {
        return min_;
      }
      /**
       * <code>double min = 3;</code>
       * @param value The min to set.
       * @return This builder for chaining.
       */
      public Builder setMin(double value) {
        
        min_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>double min = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMin() {
        bitField0_ = (bitField0_ & ~0x00000004);
        min_ = 0D;
        onChanged();
        return this;
      }

      private double max_ ;
      /**
       * <code>double max = 4;</code>
       * @return The max.
       */
      @java.lang.Override
      public double getMax() {
        return max_;
      }
      /**
       * <code>double max = 4;</code>
       * @param value The max to set.
       * @return This builder for chaining.
       */
      public Builder setMax(double value) {
        
        max_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>double max = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearMax() {
        bitField0_ = (bitField0_ & ~0x00000008);
        max_ = 0D;
        onChanged();
        return this;
      }

      private long volume_ ;
      /**
       * <code>int64 volume = 5;</code>
       * @return The volume.
       */
      @java.lang.Override
      public long getVolume() {
        return volume_;
      }
      /**
       * <code>int64 volume = 5;</code>
       * @param value The volume to set.
       * @return This builder for chaining.
       */
      public Builder setVolume(long value) {
        
        volume_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>int64 volume = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearVolume() {
        bitField0_ = (bitField0_ & ~0x00000010);
        volume_ = 0L;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>int64 timestamp = 6;</code>
       * @return The timestamp.
       */
      @java.lang.Override
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>int64 timestamp = 6;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>int64 timestamp = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000020);
        timestamp_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Aggregate)
    }

    // @@protoc_insertion_point(class_scope:Aggregate)
    private static final io.goboolean.streams.serde.Model.Aggregate DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.goboolean.streams.serde.Model.Aggregate();
    }

    public static io.goboolean.streams.serde.Model.Aggregate getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Aggregate>
        PARSER = new com.google.protobuf.AbstractParser<Aggregate>() {
      @java.lang.Override
      public Aggregate parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Aggregate> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Aggregate> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.goboolean.streams.serde.Model.Aggregate getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Trade_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Trade_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Aggregate_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Aggregate_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036src/main/resources/model.proto\"7\n\005Trad" +
      "e\022\r\n\005price\030\001 \001(\001\022\014\n\004size\030\002 \001(\003\022\021\n\ttimest" +
      "amp\030\003 \001(\003\"f\n\tAggregate\022\014\n\004open\030\001 \001(\001\022\016\n\006" +
      "closed\030\002 \001(\001\022\013\n\003min\030\003 \001(\001\022\013\n\003max\030\004 \001(\001\022\016" +
      "\n\006volume\030\005 \001(\003\022\021\n\ttimestamp\030\006 \001(\003B)\n\032io." +
      "goboolean.streams.serdeZ\013./pkg/modelb\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Trade_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Trade_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Trade_descriptor,
        new java.lang.String[] { "Price", "Size", "Timestamp", });
    internal_static_Aggregate_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Aggregate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Aggregate_descriptor,
        new java.lang.String[] { "Open", "Closed", "Min", "Max", "Volume", "Timestamp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
