name: Continuous Delivery

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Decrypt environment variables
        run: |
          echo "${{ secrets.ENV }}" base64 -d > .env

      - name: Build an app
        run: |
          make build-app