name: Continuous Integration

on:
  workflow_dispatch:
  push:
    branches:
      - feature/**
      - refactor/**

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Decrypt environment variables
        run: |
          echo "${{ secrets.ENV }}" base64 -d > .env

      - name: Run a test
        run: |
          make test-app
